id: P2A648498
initial_creation_type: input
source_metadata:
  Title: Śatagāthā
  Editor: Shastri, Losang Norbu
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2001'
  Śatagāthā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:44:37.878222'
last_modified_at: '2022-03-08T16:44:37.878230'
